#!/bin/bash

app="RAM"
me="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


# prerequisites:
#  brew
#  git
#  npm

export PATH=./node_modules/.bin:../node_modules/.bin:$PATH

case "$1" in

# SETUP

  'setup')
    echo ""
    echo "Setting up local workstation ..."
    echo ""
    npm install -g typings
    npm install -g gulp
    npm install -g bower
    echo ""
    ;;

  'deps')
    echo ""
    echo "Downloading dependencies ..."
    ./$me deps:frontend
    ./$me deps:backend
    ./$me deps:test
    echo ""
    ;;

  'deps:frontend')
    echo ""
    echo "Downloading frontend dependencies ..."
    cd frontend
    npm install && bower install && typings install && ./node_modules/.bin/jspm install
    echo ""
    ;;

  'deps:backend')
    echo ""
    echo "Downloading backend dependencies ..."
    cd backend
    npm install && typings install
    echo ""
    ;;

  'deps:test')
    echo ""
    echo "Downloading test dependencies ..."
    cd tests
    npm install && typings install
    echo ""
    ;;

# START

  'start:frontend')
    echo ""
    echo "Starting frontend"
    cd frontend
    gulp serve
    echo ""
    ;;

  'start:backend')
    echo ""
    echo "Starting backend"
    cd backend
    RAM_CONF=$DIR/backend/conf/conf-localhost.js gulp serve
    echo ""
    ;;

# TEST

  # run all API tests or, limit to one with --test <test name>
  # e.g.
  #     ./ram test:backend --test relationshipType.model
  'test:backend')
    echo ""
    echo "Starting tests"
    cd backend
    if [ -z "$3" ]
      then
        RAM_CONF=$DIR/backend/conf/conf-test.js gulp test
      else
        RAM_CONF=$DIR/backend/conf/conf-test.js gulp test "$2" "$3"
    fi
    echo ""
    ;;

  # run all API tests or, limit to one with --test <test name>
  # e.g.
  #     ./ram test:api --test relationshipType.controller
  'test:api')
    echo ""
    echo "Starting tests"
    cd tests
    if [ -z "$3" ]
      then
        gulp test
      else
        gulp test "$2" "$3"
    fi
    echo ""
    ;;

# DB

  'db:seed')
    echo ""
    echo "Seeding database"
    echo ""
    cd backend
    RAM_CONF=$DIR/backend/conf/conf-localhost.js gulp seed
    echo ""
    ;;

# OTHER

  'clean')
    echo ""
    echo "Cleaning all generated files ..."
    echo ""
    rm -rf $DIR/frontend/dist
    rm -rf $DIR/backend/dist
    rm -rf $DIR/tests/dist
    echo ""
    ;;

  'swagger')
    echo ""
    echo "Opening browser to swagger apis on local server ..."
    echo ""
    open "http://127.0.0.1:3000/api-docs/"
    echo ""
    ;;

  'staging')
    echo ""
    echo "Opening browser to staging instance ..."
    echo ""
    open "http://ramvm01.expoctest.com/#/"
    echo ""
    ;;

  'github')
    echo ""
    echo "Opening browser to github repository ..."
    echo ""
    open "https://github.com/atogov/RAM"
    echo ""
    ;;

  'wiki')
    echo ""
    echo "Opening browser to github repository ..."
    echo ""
    open "https://github.com/atogov/RAM/wiki"
    echo ""
    ;;

  'login')
    echo ""
    echo "Opening browser to mock login page ..."
    echo ""
    open "http://127.0.0.1:3001/dev/"
    echo ""
    ;;

  'travis')
    echo ""
    echo "Opening Travis continuous integration page ..."
    echo ""
    open "https://travis-ci.org/atogov/RAM"
    echo ""
    ;;

  'merge:upstream')
    echo ""
    echo "Merging from upstream ..."
    echo ""
    if [ -z "$2" ]; then
      echo "Branch not specified!"
    else
      echo "Branch: $2"
      git fetch upstream
      git merge upstream/$2 $2
    fi
    echo ""
    ;;

  *)

# USAGE

    echo -e ""
    echo "Usage:"
    echo ""
    echo "$(tput setaf 5)    $me$(tput sgr0) $(tput setaf 3)<command>$(tput sgr0)"
    echo ""
    echo "Commands:"
    echo ""
    echo "$(tput setaf 3)    setup                                $(tput sgr0)      Setups local workstation"
    echo "$(tput setaf 3)    deps                                 $(tput sgr0)      Download all dependencies"
    echo "$(tput setaf 3)    deps:frontend                        $(tput sgr0)      Download frontend dependencies"
    echo "$(tput setaf 3)    deps:backend                         $(tput sgr0)      Download backend dependencies"
    echo "$(tput setaf 3)    deps:test                            $(tput sgr0)      Download api test dependencies"
    echo ""
    echo "$(tput setaf 3)    test:backend                         $(tput sgr0)      Runs backend tests"
    echo "$(tput setaf 3)    test:api                             $(tput sgr0)      Runs API tests"
    echo ""
    echo "$(tput setaf 3)    start:frontend                       $(tput sgr0)      Starts local frontend server"
    echo "$(tput setaf 3)    start:backend                        $(tput sgr0)      Starts local backend server"
    echo ""
    echo "$(tput setaf 3)    db:seed                              $(tput sgr0)      Seeds local database"
    echo ""
    echo "$(tput setaf 3)    clean                                $(tput sgr0)      Cleans all generated files"
    echo "$(tput setaf 3)    swagger                              $(tput sgr0)      Opens browser to swagger apis on local server"
    echo "$(tput setaf 3)    staging                              $(tput sgr0)      Opens browser to staging instance"
    echo "$(tput setaf 3)    github                               $(tput sgr0)      Opens browser to github repository"
    echo "$(tput setaf 3)    wiki                                 $(tput sgr0)      Opens browser to project wiki"
    echo "$(tput setaf 3)    merge:upstream <branch>              $(tput sgr0)      Merges from upstream, <value> is branch name (eg develop)"
    echo ""
    ;;

esac

