// A RAMObject defines the common attributes that all objects in the RAM
// model will contain.
export interface  IRAMObject {
  id:                  string;    // generated by mongo
  lastUdate: {
    UserId:            string;    // reference for user who made the change
    Timestamp:         Date;      // updated by service on record change
  }
  deleted:             boolean;   // set for records to be ignored
}
