// A RAMObject defines the common attributes that all objects in the RAM
// model will contain.
export interface  IRAMObject {
  _id?:                string;    // generated by mongo
  lastUdateTimestamp?: Date;      // updated by service on record change
  deleted?:            boolean;   // set for records to be ignored
}

// A Party is the concept that participates in Relationships.
// see https://books.google.com.au/books?id=_fSVKDn7v04C&lpg=PP1&dq=enterprise%20patterns%20and%20mda%20chapter%20party%20relationship&pg=RA1-PA159#v=onepage&q=enterprise%20patterns%20and%20mda%20chapter%20party%20relationship&f=false  
export interface Party extends IRAMObject {
  roles:                  Role[];
  attributes:             {[key: string]: string};
}

interface Identity extends IRAMObject {
  type:                   string;   // "abn", scheme, ...
  value:                  string;   // abn, scheme link id
  partyId?:               string;   // index
  agencyId?:              string;   // agency the identifier is for
  //The Identity "provider" will supply a name by which to refer to
  // the party.  TBD whether RAM this record this from ABN or WofG CSPs.   
  name:                   string;
}

// Due to "Machinary of Government" changes, agencies frequently change
// their names & abbrieviations.
export interface Agency extends IRAMObject{
    currentAbbrieviation:   string;
    previousAbbrieviations: string[];
    currentName:            string;
    previousNames:          string[];
    // to be "privacy enhancing" myGov allocates different identifiers to
    // different agencies.  The consumer identifies the agency the
    // identifier is for (assuming it is relevant)
    consumer:               string;
}

// A Role is some characteristic that a Party has. Roles will only
// likely to be collected when there is something that needs to be
// build into a business rule for relationships. A Role is independant
// of relationships, e.g. you a doctor even if you have no patients.
// In essanse a Role is just a collection of attributes. 
export interface Role extends  IRAMObject{
    name:                 string;
    attributes:           {[key: string]: string};
    sharingAgencyIds:     string[];
}

//A relationship is the core concept in RAM.  
export interface Relationship extends  IRAMObject {
  type:                 string; // RelationshipType
  //A Subject is the party being effected (changed) by a
  // transaction performed by the Delegate
  subjectPartyId:       string; // indexed
  subjectRoleId:        string;
  subjectNickname:      string;
  //A Delegate is the party who will be interacting with
  // government on line services on behalf of the Subject.
  delegatePartyId:      string; // indexed
  delegateRoleId:       string;
  delegateNickname:     string;

  // Date objects for the start and end of the relationship
  startTimestamp:       Date;
  endTimestamp:         Date;

  status:               string; // indexed
  // RAM will often need to record some attributes about a Relationship,
  // e.g. what "host services" the relationship confers upon the delegate.  
  // The attributes to be recorded may be arbitaryily set by admin
  attributes:           {[key: string]: string};
  // Control for sharing various different objects in the RAM database
  // with other government agencies may be set by parties in the system.
  // The Consent object will record what agencies consent has been
  // granted for sharing.
  sharingAgencyIds:     string[];
}    

export const RelationshipType = {
  business: "Business",               //a.k.a Universal
  online:   "Online Service Provider" //a.k.a cloud appointment
}